### ISSUE TITLE
Missing other configuration tabs in Setting 

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-account#73]
# Actual Result

Some tabs used to display in Setting like Thunderbird add-ons guide, password change...is now disappearing after the frontend split. 

![screenshot_22](https://user-images.githubusercontent.com/69950655/94100377-b9245f80-fe57-11ea-8e56-186ec86dd868.png)

# Expected Result
Please confirm which tabs should display and bring them back. 

# Environment
DEV environment 
Production environment

**Comment by piavgh** [comment]
I guess this is our intention, but it needs your confirmation @MichaelBailly

**Comment by fabienmoyon** [comment]
Missing `sync` section

![Capture d’écran de 2021-04-28 19-16-07](https://user-images.githubusercontent.com/11298249/116446687-7c8a6d80-a857-11eb-90cd-8b2e84a0e872.png)

**Comment by asmaNode** [comment]
https://github.com/linagora/esn-frontend-account/pull/97/
